name: pipeline_firstApi

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: restore dep.
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore
      
