name: pipeline_firstApi

on:
  push:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

  setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        
  restore:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: restore dep.
        run: dotnet restore

  build:
    runs-on: ubuntu-latest
    needs: restore
    steps:
        - name: build
          run: dotnet build --configuration Release --no-restore
      
