name: pipeline_firstApi

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: restore dep.
      run: dotnet restore
      
    - name: build
      run: dotnet build --configuration Release --no-restore

    - name: test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Output
      run: dotnet publish -c Release -o output

    - name: publish output
      run: dotnet publish -c Release -o output
      
